name: hornborg
favicon: null
layout_spectrum: 0.4582057329826057
typography_spectrum: 0.7800911362282932
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.718398385681212
  lightness: 0.24448735266923904
  saturation: 0.5160746732726693
  rhythmicContrast: 0.16969277383759618
purpose: []
